name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main  # or the branch you want to trigger this workflow on
env:
  IMAGE_NAME: test-app
  AR_REPO_LOCATION: europe-west2
  AR_URL: 
  SERVICE_ACCOUNT: '' 
  WORKLOAD_IDENTITY_PROVIDER: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GOOLGE_PROJECT }}
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDS }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: |
        gcloud auth configure-docker ${{ env.AR_REPO_LOCATION }}-docker.pkg.dev
    
