name: Deploy nginx

on: 
  push: 
    branches: 
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
  
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: code checkout
      uses: actions/checkout@v3
    - name: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json:  ${{ secrets.GOOGLE_APPLICATION_CREDS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
        
    - name: build and push img
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOLGE_PROJECT }}
      run: |
          gcould auth configure-docker 
          docker build -t europe-west2-docker.pkg.dev/ ${{ secrets.GOOLGE_PROJECT }}/ar-test/nginx:latest .
          docker push europe-west2-docker.pkg.dev/ ${{ secrets.GOOLGE_PROJECT }}/ar-test/nginx:latest